sudo: required
services:
  - docker

before_install:
  - docker build -t aliaksandrbiarozka/react-client-test -f ./react-client/Dockerfile.dev ./react-client

script:
  - docker run -e CI=true aliaksandrbiarozka/react-client-test npm test

after_success:
  - docker build -t aliaksandrbiarozka/multi-nginx-proxy ./nginx-proxy
  - docker build -t aliaksandrbiarozka/multi-react-client ./react-client
  - docker build -t aliaksandrbiarozka/multi-server ./server 
  - docker build -t aliaksandrbiarozka/multi-worker ./worker
  # login to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and put to the docker hub
  - docker push aliaksandrbiarozka/multi-nginx-proxy
  - docker push aliaksandrbiarozka/multi-react-client
  - docker push aliaksandrbiarozka/multi-worker
  - docker push aliaksandrbiarozka/multi-server

deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-central-1-594777990648
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY