apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: postgres-deployment
  template:
    metadata:
      labels:
        component: postgres-deployment
    spec:
      volumes:
        - name:  postgress-storage
          persistentVolumeClaim:
            claimName: database-persistent-volume-cliam
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgress-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword-secret
                  key: PG_PASSWORD